"""Public typed API for Astro host composition."""

from astro_host.conditions import ConditionsService
from astro_host.equipment import (
    EquipmentStore,
    FileEquipmentStore,
    MemoryEquipmentStore,
    canonicalize_equipment_id,
    default_equipment_path,
)
from astro_host.equipment_session import EquipmentSessionService, compose_active
from astro_host.errors import (
    EquipmentConflictError,
    EquipmentNotFoundError,
    EquipmentStoreCorruptError,
    EquipmentStoreError,
    EquipmentStoreUnsupportedSchemaError,
    InvalidEquipmentError,
    InvalidLocationError,
    InvalidPlaceCandidateError,
    InvalidProviderTimezoneError,
    LocationConflictError,
    LocationNotFoundError,
    LocationStoreCorruptError,
    LocationStoreError,
    LocationStoreUnsupportedSchemaError,
    NoSelectedLocationError,
    PlaceProviderError,
)
from astro_host.locations import (
    FileLocationStore,
    LocationStore,
    MemoryLocationStore,
    canonicalize_location_id,
    default_locations_path,
    normalize_label,
)
from astro_host.models import (
    ActiveEquipment,
    ConditionsRequest,
    ConditionsResult,
    EquipmentApertureUnit,
    EquipmentOverride,
    EquipmentOverrideMode,
    EquipmentSelection,
    EquipmentSelectionMode,
    EquipmentState,
    HostConditionsRequest,
    InlineEquipmentDraft,
    Location,
    LocationSource,
    LocationState,
    PlaceCandidate,
    PlaceConfirmRequest,
    PlaceResolution,
    EquipmentType,
    SavedEquipment,
    SavedEquipmentDraft,
    SavedLocation,
    SavedLocationDraft,
)
from astro_host.places import ObservingLocationService

__all__ = [
    "ActiveEquipment",
    "ConditionsRequest",
    "ConditionsResult",
    "ConditionsService",
    "EquipmentApertureUnit",
    "EquipmentConflictError",
    "EquipmentNotFoundError",
    "EquipmentOverride",
    "EquipmentOverrideMode",
    "EquipmentSelection",
    "EquipmentSelectionMode",
    "EquipmentSessionService",
    "EquipmentState",
    "EquipmentStore",
    "EquipmentStoreCorruptError",
    "EquipmentStoreError",
    "EquipmentStoreUnsupportedSchemaError",
    "EquipmentType",
    "FileEquipmentStore",
    "FileLocationStore",
    "HostConditionsRequest",
    "InlineEquipmentDraft",
    "InvalidEquipmentError",
    "InvalidLocationError",
    "InvalidPlaceCandidateError",
    "InvalidProviderTimezoneError",
    "Location",
    "LocationConflictError",
    "LocationNotFoundError",
    "LocationSource",
    "LocationState",
    "LocationStore",
    "LocationStoreCorruptError",
    "LocationStoreError",
    "LocationStoreUnsupportedSchemaError",
    "MemoryEquipmentStore",
    "MemoryLocationStore",
    "NoSelectedLocationError",
    "ObservingLocationService",
    "PlaceCandidate",
    "PlaceConfirmRequest",
    "PlaceProviderError",
    "PlaceResolution",
    "SavedEquipment",
    "SavedEquipmentDraft",
    "SavedLocation",
    "SavedLocationDraft",
    "canonicalize_equipment_id",
    "canonicalize_location_id",
    "compose_active",
    "default_equipment_path",
    "default_locations_path",
    "normalize_label",
]
